[workspace]
resolver = "2"

members = ["day*"]

[workspace.dependencies]
itertools = "0.12.0"
nom = "7.1.3"
num = "0.4"
glam = "0.24"
indicatif = {  version = "0.17", features = ["rayon"] }
rayon = "1.8.0"
memoize = "0.4"
indexmap = "2.1"
pathfinding = "4.6"