set dotenv-load

alias d := dev
alias b := build
# alias t := test
alias r := run
alias p := profile
alias s := scaffold

dev day part:
    cabal repl {{day}}:{{part}}
build day part:
    cabal build {{day}}:{{part}}
# test day part="":
#     cargo test -p {{day}} {{ if part == "" { "--bins" } else { "--bin " } }}{{part}} -- --show-output
run day part:
    cabal run {{day}}:{{part}}
profile day part:
    cabal build {{day}}:{{part}} --enable-profiling --ghc-options="-fprof-auto -rtsopts"
    cabal run {{day}}:{{part}} --enable-profiling -- +RTS -p -hc 
scaffold day:
    ./scripts/scaffold.sh {{day}}
    just fetch-input {{day}}    
fetch-input day:
    ./scripts/fetch-input.sh {{day}} $SESSION